import gleam/list
import gleam/option.{None, Some}
import gleam/string
import gleeunit/should
import nori/codegen/ir.{
  type CodegenIR, CodegenIR, Endpoint, EndpointParam, EnumVariant, Field, Named,
  Primitive, RecordType, RequestBodyIR, ResponseIR,
}
import nori/codegen/templates
import nori/codegen/typescript/fetch_client
import nori/codegen/typescript/react_query
import nori/codegen/typescript/types

fn sample_ir() -> CodegenIR {
  CodegenIR(
    title: "Pet Store",
    version: "1.0.0",
    base_url: Some("https://api.example.com"),
    types: [
      RecordType(
        name: "Pet",
        fields: [
          Field(
            name: "id",
            type_ref: Primitive(ir.PInt),
            required: True,
            description: None,
            read_only: False,
            write_only: False,
          ),
          Field(
            name: "name",
            type_ref: Primitive(ir.PString),
            required: True,
            description: Some("The pet name"),
            read_only: False,
            write_only: False,
          ),
          Field(
            name: "tag",
            type_ref: Primitive(ir.PString),
            required: False,
            description: None,
            read_only: False,
            write_only: False,
          ),
        ],
        description: Some("A pet in the store"),
      ),
      ir.EnumType(
        name: "Status",
        variants: [
          EnumVariant(name: "Active", value: "active"),
          EnumVariant(name: "Inactive", value: "inactive"),
        ],
        description: None,
      ),
    ],
    endpoints: [
      Endpoint(
        operation_id: "list_pets",
        method: ir.Get,
        path: "/pets",
        summary: Some("List all pets"),
        description: None,
        tags: ["pets"],
        parameters: [
          EndpointParam(
            name: "limit",
            location: ir.QueryParam,
            type_ref: Primitive(ir.PInt),
            required: False,
            description: None,
          ),
        ],
        request_body: None,
        responses: [
          ResponseIR(
            status_code: "200",
            description: "A list of pets",
            content_type: Some("application/json"),
            type_ref: Some(ir.Array(Named("Pet"))),
          ),
        ],
        deprecated: False,
        security: None,
      ),
      Endpoint(
        operation_id: "create_pet",
        method: ir.Post,
        path: "/pets",
        summary: Some("Create a pet"),
        description: None,
        tags: ["pets"],
        parameters: [],
        request_body: Some(RequestBodyIR(
          content_type: "application/json",
          type_ref: Named("Pet"),
          required: True,
        )),
        responses: [
          ResponseIR(
            status_code: "201",
            description: "Created",
            content_type: Some("application/json"),
            type_ref: Some(Named("Pet")),
          ),
        ],
        deprecated: False,
        security: None,
      ),
      Endpoint(
        operation_id: "show_pet_by_id",
        method: ir.Get,
        path: "/pets/{petId}",
        summary: Some("Info for a specific pet"),
        description: None,
        tags: ["pets"],
        parameters: [
          EndpointParam(
            name: "petId",
            location: ir.PathParam,
            type_ref: Primitive(ir.PString),
            required: True,
            description: None,
          ),
        ],
        request_body: None,
        responses: [
          ResponseIR(
            status_code: "200",
            description: "Expected response to a valid request",
            content_type: Some("application/json"),
            type_ref: Some(Named("Pet")),
          ),
        ],
        deprecated: False,
        security: None,
      ),
    ],
    security_schemes: [],
    global_security: [],
  )
}

// Types generation tests

pub fn generate_types_contains_interface_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("export interface Pet {")
  |> should.be_true

  output
  |> string.contains("id: number;")
  |> should.be_true

  output
  |> string.contains("name: string;")
  |> should.be_true

  output
  |> string.contains("tag?: string;")
  |> should.be_true
}

pub fn generate_types_contains_header_test() {
  let output = types.generate(sample_ir())

  // Exactly one banner: the generators prepend it, so the templates must not
  // carry one of their own.
  output
  |> string.split("- Do not edit manually")
  |> list.length
  |> should.equal(2)

  output
  |> string.starts_with("// Generated by nori - Do not edit manually")
  |> should.be_true
}

pub fn generate_types_contains_enum_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("export type Status = ")
  |> should.be_true

  output
  |> string.contains("\"active\"")
  |> should.be_true
}

pub fn generate_types_description_comment_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("/** A pet in the store */")
  |> should.be_true

  output
  |> string.contains("/** The pet name */")
  |> should.be_true
}

// React Query hooks generation tests

pub fn generate_react_query_has_query_hook_test() {
  let output = react_query.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("export function useListPets(")
  |> should.be_true

  output
  |> string.contains("useQuery<")
  |> should.be_true
}

pub fn generate_react_query_has_mutation_hook_test() {
  let output = react_query.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("export function useCreatePet(")
  |> should.be_true

  output
  |> string.contains("useMutation<")
  |> should.be_true
}

pub fn generate_react_query_has_show_hook_test() {
  let output = react_query.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("export function useShowPetById(")
  |> should.be_true
}

pub fn generate_react_query_imports_test() {
  let output = react_query.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("from \"@tanstack/react-query\"")
  |> should.be_true

  output
  |> string.contains("from \"./types.generated\"")
  |> should.be_true

  output
  |> string.contains("from \"./client.generated\"")
  |> should.be_true
}

// Fetch client generation tests

pub fn generate_fetch_client_no_cookie_auth_test() {
  // Without cookie auth, credentials default to undefined and surface the
  // override knob without forcing "include".
  let output =
    fetch_client.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("credentials?: RequestCredentials;")
  |> should.be_true

  output
  |> string.contains("baseUrl: \"\", credentials: undefined")
  |> should.be_true

  output
  |> string.contains("credentials: _config.credentials,")
  |> should.be_true

  // Improved error body parsing
  output
  |> string.contains("await response.clone().json()")
  |> should.be_true
}

pub fn generate_fetch_client_cookie_auth_test() {
  // With ApiKeyAuth(_, _, InCookie), the generated client defaults
  // credentials to "include" so the browser sends the session cookie.
  let base = sample_ir()
  let with_cookie =
    CodegenIR(..base, security_schemes: [
      ir.ApiKeyAuth(
        name: "cookieAuth",
        param_name: "session",
        location: ir.InCookie,
      ),
    ])

  let output =
    fetch_client.generate(with_cookie, templates.default_ts_modules())

  output
  |> string.contains("credentials: _config.credentials ?? \"include\"")
  |> should.be_true

  output
  |> string.contains("baseUrl: \"\", credentials: \"include\"")
  |> should.be_true
}

pub fn generate_react_query_honours_no_generated_suffix_test() {
  // With generated_suffix: false the files on disk are types.ts and client.ts,
  // so importing ./types.generated names a file that was never written.
  let output =
    react_query.generate(sample_ir(), templates.ts_modules_for_suffix(False))

  output
  |> string.contains("from \"./types\"")
  |> should.be_true

  output
  |> string.contains("from \"./client\"")
  |> should.be_true

  output
  |> string.contains(".generated\"")
  |> should.be_false
}

pub fn generate_react_query_query_key_includes_params_test() {
  // Without params in the key, changing a filter or cursor reads the previous
  // page out of cache and never refetches.
  let output = react_query.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("queryKey: [\"list_pets\", params]")
  |> should.be_true

  // Operations with no query params keep their existing key shape.
  output
  |> string.contains("queryKey: [\"show_pet_by_id\", petId]")
  |> should.be_true
}

pub fn generate_fetch_client_relative_base_url_test() {
  // new URL(relative) throws, so query-param operations must not use it —
  // baseUrl: "/api/v1" is the ordinary same-origin configuration.
  let output =
    fetch_client.generate(sample_ir(), templates.default_ts_modules())

  output
  |> string.contains("new URL(")
  |> should.be_false

  output
  |> string.contains("const _query = new URLSearchParams();")
  |> should.be_true

  output
  |> string.contains(
    "if (params.limit !== undefined) _query.set(\"limit\", String(params.limit));",
  )
  |> should.be_true

  output
  |> string.contains(
    "const url = `${_config.baseUrl}/pets${_qs ? `?${_qs}` : \"\"}`;",
  )
  |> should.be_true
}

pub fn generate_fetch_client_honours_no_generated_suffix_test() {
  let output =
    fetch_client.generate(sample_ir(), templates.ts_modules_for_suffix(False))

  output
  |> string.contains("from \"./types\"")
  |> should.be_true
}
