import gleam/option.{None, Some}
import gleam/string
import gleeunit/should
import nori/codegen/ir.{
  type CodegenIR, CodegenIR, Endpoint, EndpointParam, EnumVariant, Field, Named,
  Primitive, RecordType, RequestBodyIR, ResponseIR,
}
import nori/codegen/typescript/react_query
import nori/codegen/typescript/types

fn sample_ir() -> CodegenIR {
  CodegenIR(
    title: "Pet Store",
    version: "1.0.0",
    base_url: Some("https://api.example.com"),
    types: [
      RecordType(
        name: "Pet",
        fields: [
          Field(
            name: "id",
            type_ref: Primitive(ir.PInt),
            required: True,
            description: None,
            read_only: False,
            write_only: False,
          ),
          Field(
            name: "name",
            type_ref: Primitive(ir.PString),
            required: True,
            description: Some("The pet name"),
            read_only: False,
            write_only: False,
          ),
          Field(
            name: "tag",
            type_ref: Primitive(ir.PString),
            required: False,
            description: None,
            read_only: False,
            write_only: False,
          ),
        ],
        description: Some("A pet in the store"),
      ),
      ir.EnumType(
        name: "Status",
        variants: [
          EnumVariant(name: "Active", value: "active"),
          EnumVariant(name: "Inactive", value: "inactive"),
        ],
        description: None,
      ),
    ],
    endpoints: [
      Endpoint(
        operation_id: "list_pets",
        method: ir.Get,
        path: "/pets",
        summary: Some("List all pets"),
        description: None,
        tags: ["pets"],
        parameters: [
          EndpointParam(
            name: "limit",
            location: ir.QueryParam,
            type_ref: Primitive(ir.PInt),
            required: False,
            description: None,
          ),
        ],
        request_body: None,
        responses: [
          ResponseIR(
            status_code: "200",
            description: "A list of pets",
            content_type: Some("application/json"),
            type_ref: Some(ir.Array(Named("Pet"))),
          ),
        ],
        deprecated: False,
        security: None,
      ),
      Endpoint(
        operation_id: "create_pet",
        method: ir.Post,
        path: "/pets",
        summary: Some("Create a pet"),
        description: None,
        tags: ["pets"],
        parameters: [],
        request_body: Some(RequestBodyIR(
          content_type: "application/json",
          type_ref: Named("Pet"),
          required: True,
        )),
        responses: [
          ResponseIR(
            status_code: "201",
            description: "Created",
            content_type: Some("application/json"),
            type_ref: Some(Named("Pet")),
          ),
        ],
        deprecated: False,
        security: None,
      ),
      Endpoint(
        operation_id: "show_pet_by_id",
        method: ir.Get,
        path: "/pets/{petId}",
        summary: Some("Info for a specific pet"),
        description: None,
        tags: ["pets"],
        parameters: [
          EndpointParam(
            name: "petId",
            location: ir.PathParam,
            type_ref: Primitive(ir.PString),
            required: True,
            description: None,
          ),
        ],
        request_body: None,
        responses: [
          ResponseIR(
            status_code: "200",
            description: "Expected response to a valid request",
            content_type: Some("application/json"),
            type_ref: Some(Named("Pet")),
          ),
        ],
        deprecated: False,
        security: None,
      ),
    ],
    security_schemes: [],
    global_security: [],
  )
}

// Types generation tests

pub fn generate_types_contains_interface_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("export interface Pet {")
  |> should.be_true

  output
  |> string.contains("id: number;")
  |> should.be_true

  output
  |> string.contains("name: string;")
  |> should.be_true

  output
  |> string.contains("tag?: string;")
  |> should.be_true
}

pub fn generate_types_contains_header_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("// Generated by openapi - Do not edit manually")
  |> should.be_true
}

pub fn generate_types_contains_enum_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("export type Status = ")
  |> should.be_true

  output
  |> string.contains("\"active\"")
  |> should.be_true
}

pub fn generate_types_description_comment_test() {
  let output = types.generate(sample_ir())

  output
  |> string.contains("/** A pet in the store */")
  |> should.be_true

  output
  |> string.contains("/** The pet name */")
  |> should.be_true
}

// React Query hooks generation tests

pub fn generate_react_query_has_query_hook_test() {
  let output = react_query.generate(sample_ir())

  output
  |> string.contains("export function useListPets(")
  |> should.be_true

  output
  |> string.contains("useQuery<")
  |> should.be_true
}

pub fn generate_react_query_has_mutation_hook_test() {
  let output = react_query.generate(sample_ir())

  output
  |> string.contains("export function useCreatePet(")
  |> should.be_true

  output
  |> string.contains("useMutation<")
  |> should.be_true
}

pub fn generate_react_query_has_show_hook_test() {
  let output = react_query.generate(sample_ir())

  output
  |> string.contains("export function useShowPetById(")
  |> should.be_true
}

pub fn generate_react_query_imports_test() {
  let output = react_query.generate(sample_ir())

  output
  |> string.contains("from \"@tanstack/react-query\"")
  |> should.be_true

  output
  |> string.contains("from \"./types.generated\"")
  |> should.be_true

  output
  |> string.contains("from \"./client.generated\"")
  |> should.be_true
}
