// Generated by openapi - Do not edit manually

import type { Comment, CreateCommentRequest, CreatePostRequest, CreateUserRequest, Error, Post, PostStatus, UpdateUserRequest, User } from "./types.generated";

export interface ClientConfig {
  baseUrl: string;
  headers?: Record<string, string>;
}

let _config: ClientConfig = { baseUrl: "" };

export function configure(config: ClientConfig): void {
  _config = config;
}

function getHeaders(): Record<string, string> {
  return {
    "Content-Type": "application/json",
    ...(_config.headers ?? {}),
  };
}

/** Create a new post */
export async function createPost(body: CreatePostRequest): Promise<Post> {
  const url = `${_config.baseUrl}/posts`;
  const response = await fetch(url, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Post;
}

/** List all posts */
export async function listPosts(params: { page?: number; per_page?: number; sort?: string; status?: PostStatus }): Promise<Array<Post>> {
  const _url = new URL(`${_config.baseUrl}/posts`);
  if (params.page !== undefined) _url.searchParams.set("page", String(params.page));
  if (params.per_page !== undefined) _url.searchParams.set("per_page", String(params.per_page));
  if (params.sort !== undefined) _url.searchParams.set("sort", String(params.sort));
  if (params.status !== undefined) _url.searchParams.set("status", String(params.status));
  const url = _url.toString();
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Array<Post>;
}

/** Delete a post */
export async function deletePost(postId: string): Promise<void> {
  const url = `${_config.baseUrl}/posts/${postId}`;
  const response = await fetch(url, {
    method: "DELETE",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return;
}

/** Update an existing post */
export async function updatePost(postId: string, body: CreatePostRequest): Promise<Post> {
  const url = `${_config.baseUrl}/posts/${postId}`;
  const response = await fetch(url, {
    method: "PUT",
    headers: getHeaders(),
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Post;
}

/** Get a post by ID */
export async function getPost(postId: string): Promise<Post> {
  const url = `${_config.baseUrl}/posts/${postId}`;
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Post;
}

/** Add a comment to a post */
export async function createComment(postId: string, body: CreateCommentRequest): Promise<Comment> {
  const url = `${_config.baseUrl}/posts/${postId}/comments`;
  const response = await fetch(url, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Comment;
}

/** List comments on a post */
export async function listComments(postId: string, params: { page?: number; per_page?: number }): Promise<Array<Comment>> {
  const _url = new URL(`${_config.baseUrl}/posts/${postId}/comments`);
  if (params.page !== undefined) _url.searchParams.set("page", String(params.page));
  if (params.per_page !== undefined) _url.searchParams.set("per_page", String(params.per_page));
  const url = _url.toString();
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Array<Comment>;
}

/** Create a new user */
export async function createUser(body: CreateUserRequest): Promise<User> {
  const url = `${_config.baseUrl}/users`;
  const response = await fetch(url, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as User;
}

/** List all users */
export async function listUsers(params: { page?: number; per_page?: number; sort?: string }): Promise<Array<User>> {
  const _url = new URL(`${_config.baseUrl}/users`);
  if (params.page !== undefined) _url.searchParams.set("page", String(params.page));
  if (params.per_page !== undefined) _url.searchParams.set("per_page", String(params.per_page));
  if (params.sort !== undefined) _url.searchParams.set("sort", String(params.sort));
  const url = _url.toString();
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Array<User>;
}

/** Delete a user */
export async function deleteUser(userId: string): Promise<void> {
  const url = `${_config.baseUrl}/users/${userId}`;
  const response = await fetch(url, {
    method: "DELETE",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return;
}

/** Update an existing user */
export async function updateUser(userId: string, body: UpdateUserRequest): Promise<User> {
  const url = `${_config.baseUrl}/users/${userId}`;
  const response = await fetch(url, {
    method: "PUT",
    headers: getHeaders(),
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as User;
}

/** Get a user by ID */
export async function getUser(userId: string): Promise<User> {
  const url = `${_config.baseUrl}/users/${userId}`;
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as User;
}
