// Generated by openapi - Do not edit manually

import { useQuery, useMutation } from "@tanstack/react-query";
import type { Comment, CreateCommentRequest, CreatePostRequest, CreateUserRequest, Error, Post, PostStatus, UpdateUserRequest, User } from "./types.generated";
import { createPost, listPosts, deletePost, updatePost, getPost, createComment, listComments, createUser, listUsers, deleteUser, updateUser, getUser } from "./client.generated";

export const postsKeys = {
  all: ["posts"] as const,
  lists: () => [...postsKeys.all, "list"] as const,
  details: () => [...postsKeys.all, "detail"] as const,
  detail: (id: string | number) => [...postsKeys.details(), id] as const,
};

export const commentsKeys = {
  all: ["comments"] as const,
  lists: () => [...commentsKeys.all, "list"] as const,
  details: () => [...commentsKeys.all, "detail"] as const,
  detail: (id: string | number) => [...commentsKeys.details(), id] as const,
};

export const usersKeys = {
  all: ["users"] as const,
  lists: () => [...usersKeys.all, "list"] as const,
  details: () => [...usersKeys.all, "detail"] as const,
  detail: (id: string | number) => [...usersKeys.details(), id] as const,
};

/** Create a new post */
export function useCreatePost() {
  return useMutation<Post, Error, { body: CreatePostRequest }>({
    mutationFn: (vars) => createPost(vars.body),
  });
}

/** List all posts */
export function useListPosts(params: { page?: number; per_page?: number; sort?: string; status?: PostStatus }) {
  return useQuery<Array<Post>>({
    queryKey: ["listPosts"],
    queryFn: () => listPosts(params),
  });
}

/** Delete a post */
export function useDeletePost() {
  return useMutation<void, Error, { postId: string }>({
    mutationFn: (vars) => deletePost(vars.postId),
  });
}

/** Update an existing post */
export function useUpdatePost() {
  return useMutation<Post, Error, { postId: string; body: CreatePostRequest }>({
    mutationFn: (vars) => updatePost(vars.postId, vars.body),
  });
}

/** Get a post by ID */
export function useGetPost(postId: string) {
  return useQuery<Post>({
    queryKey: ["getPost", postId],
    queryFn: () => getPost(postId),
  });
}

/** Add a comment to a post */
export function useCreateComment() {
  return useMutation<Comment, Error, { postId: string; body: CreateCommentRequest }>({
    mutationFn: (vars) => createComment(vars.postId, vars.body),
  });
}

/** List comments on a post */
export function useListComments(postId: string, params: { page?: number; per_page?: number }) {
  return useQuery<Array<Comment>>({
    queryKey: ["listComments", postId],
    queryFn: () => listComments(postId, params),
  });
}

/** Create a new user */
export function useCreateUser() {
  return useMutation<User, Error, { body: CreateUserRequest }>({
    mutationFn: (vars) => createUser(vars.body),
  });
}

/** List all users */
export function useListUsers(params: { page?: number; per_page?: number; sort?: string }) {
  return useQuery<Array<User>>({
    queryKey: ["listUsers"],
    queryFn: () => listUsers(params),
  });
}

/** Delete a user */
export function useDeleteUser() {
  return useMutation<void, Error, { userId: string }>({
    mutationFn: (vars) => deleteUser(vars.userId),
  });
}

/** Update an existing user */
export function useUpdateUser() {
  return useMutation<User, Error, { userId: string; body: UpdateUserRequest }>({
    mutationFn: (vars) => updateUser(vars.userId, vars.body),
  });
}

/** Get a user by ID */
export function useGetUser(userId: string) {
  return useQuery<User>({
    queryKey: ["getUser", userId],
    queryFn: () => getUser(userId),
  });
}
