// Generated by openapi - Do not edit manually

import useSWR from "swr";
import useSWRMutation from "swr/mutation";
import type { Comment, CreateCommentRequest, CreatePostRequest, CreateUserRequest, Error, Post, PostStatus, UpdateUserRequest, User } from "./types.generated";
import { createPost, listPosts, deletePost, updatePost, getPost, createComment, listComments, createUser, listUsers, deleteUser, updateUser, getUser } from "./client.generated";

/** Create a new post */
export function useCreatePost() {
  return useSWRMutation<Post, Error, string, { body: CreatePostRequest }>("createPost", (_key, { arg }) => createPost(arg.body));
}

/** List all posts */
export function useListPosts(params: { page?: number; per_page?: number; sort?: string; status?: PostStatus }) {
  return useSWR<Array<Post>>("listPosts", () => listPosts(params));
}

/** Delete a post */
export function useDeletePost() {
  return useSWRMutation<void, Error, string, { postId: string }>("deletePost", (_key, { arg }) => deletePost(arg.postId));
}

/** Update an existing post */
export function useUpdatePost() {
  return useSWRMutation<Post, Error, string, { postId: string; body: CreatePostRequest }>("updatePost", (_key, { arg }) => updatePost(arg.postId, arg.body));
}

/** Get a post by ID */
export function useGetPost(postId: string) {
  return useSWR<Post>(["getPost", postId], () => getPost(postId));
}

/** Add a comment to a post */
export function useCreateComment() {
  return useSWRMutation<Comment, Error, string, { postId: string; body: CreateCommentRequest }>("createComment", (_key, { arg }) => createComment(arg.postId, arg.body));
}

/** List comments on a post */
export function useListComments(postId: string, params: { page?: number; per_page?: number }) {
  return useSWR<Array<Comment>>(["listComments", postId], () => listComments(postId, params));
}

/** Create a new user */
export function useCreateUser() {
  return useSWRMutation<User, Error, string, { body: CreateUserRequest }>("createUser", (_key, { arg }) => createUser(arg.body));
}

/** List all users */
export function useListUsers(params: { page?: number; per_page?: number; sort?: string }) {
  return useSWR<Array<User>>("listUsers", () => listUsers(params));
}

/** Delete a user */
export function useDeleteUser() {
  return useSWRMutation<void, Error, string, { userId: string }>("deleteUser", (_key, { arg }) => deleteUser(arg.userId));
}

/** Update an existing user */
export function useUpdateUser() {
  return useSWRMutation<User, Error, string, { userId: string; body: UpdateUserRequest }>("updateUser", (_key, { arg }) => updateUser(arg.userId, arg.body));
}

/** Get a user by ID */
export function useGetUser(userId: string) {
  return useSWR<User>(["getUser", userId], () => getUser(userId));
}
