// Generated by openapi - Do not edit manually

export interface Comment {
  author: User;
  body: string;
  created_at: string;
  id: string;
}

export interface CreateCommentRequest {
  body: string;
}

export interface CreatePostRequest {
  body: string;
  status?: PostStatus;
  tags?: Array<string>;
  title: string;
}

export interface CreateUserRequest {
  bio?: string;
  email: string;
  password: string;
  username: string;
}

export interface Error {
  code: number;
  details?: Array<string>;
  message: string;
}

export interface Post {
  author: User;
  body: string;
  created_at: string;
  id: string;
  status: PostStatus;
  tags?: Array<string>;
  title: string;
  updated_at?: string;
}

export type PostStatus = "draft" | "published" | "archived";

export interface UpdateUserRequest {
  avatar_url?: string | null;
}

export interface User {
  avatar_url?: string | null;
  bio?: string;
  created_at: string;
  email: string;
  id: string;
  updated_at?: string;
  username: string;
}
