// Generated by openapi - Do not edit manually

import type { CreatePetRequest, Error, Pet } from "./types.generated";

export interface ClientConfig {
  baseUrl: string;
  headers?: Record<string, string>;
}

let _config: ClientConfig = { baseUrl: "" };

export function configure(config: ClientConfig): void {
  _config = config;
}

function getHeaders(): Record<string, string> {
  return {
    "Content-Type": "application/json",
    ...(_config.headers ?? {}),
  };
}

/** Create a pet */
export async function createPet(body: CreatePetRequest): Promise<void> {
  const url = `${_config.baseUrl}/pets`;
  const response = await fetch(url, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return;
}

/** List all pets */
export async function listPets(params: { limit?: number }): Promise<Array<Pet>> {
  const _url = new URL(`${_config.baseUrl}/pets`);
  if (params.limit !== undefined) _url.searchParams.set("limit", String(params.limit));
  const url = _url.toString();
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Array<Pet>;
}

/** Info for a specific pet */
export async function showPetById(petId: string): Promise<Pet> {
  const url = `${_config.baseUrl}/pets/${petId}`;
  const response = await fetch(url, {
    method: "GET",
    headers: getHeaders(),
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return await response.json() as Pet;
}
