// Generated by openapi - Do not edit manually

import { useQuery, useMutation } from "@tanstack/react-query";
import type { CreatePetRequest, Error, Pet } from "./types.generated";
import { createPet, listPets, showPetById } from "./client.generated";

export const petsKeys = {
  all: ["pets"] as const,
  lists: () => [...petsKeys.all, "list"] as const,
  details: () => [...petsKeys.all, "detail"] as const,
  detail: (id: string | number) => [...petsKeys.details(), id] as const,
};

/** Create a pet */
export function useCreatePet() {
  return useMutation<void, Error, { body: CreatePetRequest }>({
    mutationFn: (vars) => createPet(vars.body),
  });
}

/** List all pets */
export function useListPets(params: { limit?: number }) {
  return useQuery<Array<Pet>>({
    queryKey: ["listPets"],
    queryFn: () => listPets(params),
  });
}

/** Info for a specific pet */
export function useShowPetById(petId: string) {
  return useQuery<Pet>({
    queryKey: ["showPetById", petId],
    queryFn: () => showPetById(petId),
  });
}
