// Generated by openapi - Do not edit manually

import useSWR from "swr";
import useSWRMutation from "swr/mutation";
import type { CreatePetRequest, Error, Pet } from "./types.generated";
import { createPet, listPets, showPetById } from "./client.generated";

/** Create a pet */
export function useCreatePet() {
  return useSWRMutation<void, Error, string, { body: CreatePetRequest }>("createPet", (_key, { arg }) => createPet(arg.body));
}

/** List all pets */
export function useListPets(params: { limit?: number }) {
  return useSWR<Array<Pet>>("listPets", () => listPets(params));
}

/** Info for a specific pet */
export function useShowPetById(petId: string) {
  return useSWR<Pet>(["showPetById", petId], () => showPetById(petId));
}
