// Generated by openapi - Do not edit manually

export interface CreatePetRequest {
  name: string;
  tag?: string;
}

export interface Error {
  code: number;
  message: string;
}

export interface Pet {
  id: number;
  name: string;
  tag?: string;
}
